/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 obj.gltf 
Author: SerDante (https://sketchfab.com/streetvolf69)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/qs-acbfa9e466034e2fa8b3be687da1c29a
Title: Qs
*/

import {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

export function Obj(props: any) {
    const {nodes, materials}: any = useGLTF(import.meta.env.BASE_URL + 'obj.gltf');

    const objRef = useRef<any>();

    useFrame((_, delta) => {
        objRef.current.rotation.y += 0.2 * delta
    })

    return (
        <group {...props} dispose={null} ref={objRef}>
            <group rotation={[Math.PI, 0, Math.PI / 2]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-1.524, 2.41, -0.003]} rotation={[-Math.PI, 1.463, -Math.PI / 2]}
                           scale={[1.312, 1, 1]}>
                        <mesh geometry={nodes.Object_7.geometry} material={materials.material_1}
                              rotation={[-0.11, 0.004, -1.576]}/>
                    </group>
                    <group position={[-0.934, 0.363, 0.609]} rotation={[0, Math.PI / 3, -Math.PI / 2]}>
                        <mesh geometry={nodes.Object_13.geometry} material={materials.material_4}/>
                        <mesh geometry={nodes.Object_14.geometry} material={materials.material_4}/>
                    </group>
                    <mesh geometry={nodes.Object_4.geometry} material={materials.material_0}
                          position={[-0.427, 1.793, -0.299]}/>
                    <mesh geometry={nodes.Object_9.geometry} material={materials.material_2}
                          position={[-0.427, 1.793, -0.701]}/>
                    <mesh geometry={nodes.Object_11.geometry} material={materials.material_3}
                          position={[-0.396, 4.77, -0.299]}/>
                    <mesh geometry={nodes.Object_16.geometry} material={materials.material_5}
                          position={[-0.386, 4.77, -0.721]}/>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(import.meta.env.BASE_URL + '/obj.gltf')
